version: "3.9"

networks:
  onpe-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onpe-app
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - PORT=${PORT:-3001}
    volumes:
      - ./db.json:/app/db.json
      - ./public:/app/public
      - ./logs.txt:/app/logs.txt
    restart: unless-stopped
    networks:
      - onpe-network

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: gpt-tokens-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    depends_on:
      - app
    networks:
      - onpe-network
