version: "3.9"

networks:
  onpe-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onpe-app
    volumes:
      - ./db.json:/app/db.json
      - ./public:/app/public
      - ./logs.txt:/app/logs.txt
    restart: unless-stopped
    networks:
      - onpe-network

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-onpe-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    depends_on:
      - app
    networks:
      - onpe-network
